### ISSUE TITLE
Main csv file missing many exoplanets

### ISSUE THREAD

**Issue by astrofrog** [OpenExoplanetCatalogue/oec_tables#6]
The main CSV file has had many objects removed during an automated update last year:

https://github.com/OpenExoplanetCatalogue/oec_tables/commit/50facd9c5ba1237c9540f599620a124b6ffc83a1#diff-1eb0b91e2aae65baab769e3d38e5e6ec

Was this deliberate?

**Comment by hannorein** [comment]
I don't remember. 

I'm actually working on an overhaul of the entire pipeline right now. The idea is to always pull in changes from the NASA exoplanet archive and then substitute it with additional data. That will probably take care of this issue too.
