### ISSUE TITLE
The Ascii file for the oec_tables does not contain records for all the exoplanets

### ISSUE THREAD

**Issue by kulturedyobbo** [OpenExoplanetCatalogue/oec_tables#7]
Hi there.

Great website. 

I noticed for quite a while that the ascii file for the oec_tables does not contain all the records for all the exoplanets. It only has records for about 1616 when the number should be 3504.

Cheers

**Comment by hannorein** [comment]
I'm not sure if this was a temporary issue or not, but now the table seems to have all exoplanets again.

**Comment by kulturedyobbo** [comment]
Hi Hanno

Yes it does now.

Happy New Year.

Cheers
